name: flutter_alarm
description: A new Flutter project for an alarm clock app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  audioplayers: ^5.2.1
  file_picker: ^6.1.1
  permission_handler: ^11.3.1
  android_alarm_manager_plus: ^4.0.7
  flutter_local_notifications: ^19.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/alarm1.mp3
    - assets/sounds/alarm2.mp3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"